// <auto-generated />
namespace TASEF.Migrations.OtherDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stateEDR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stateEDR));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201800066_stateEDR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
